"""
AI Solution Builder — Real Data Layer Generation

Replaces the fake Next.js layer that made every generated app look alive while
doing nothing:

  before: /api/v1/* handled inside Next by an in-memory object seeded with
          ice-cream sample rows; action routes returned `output_example`
          verbatim, so "work out the bill" always replied with the same number.

  after:  /api/v1/* in Next is a thin proxy to the FastAPI service, which owns
          the database and the business rules. Seed rows come only from the
          user's own spec. Actions have no generated handler at all — they live
          in backend/actions.py where the acceptance tests can gate them.

Import these in place of `spec_codegen.gen_next_route_handlers`.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

# ── Next.js proxy: one catch-all that forwards to FastAPI ───────────────

_PROXY_ROUTE_TS = """// @generated by AI Solution Builder
// Forwards every /api/v1/* call to the application server, which owns the
// database and the business rules. Nothing is stored in this file.

import { NextRequest, NextResponse } from "next/server";

export const dynamic = "force-dynamic";

const BACKEND =
  process.env.BACKEND_URL ||
  process.env.NEXT_PUBLIC_API_URL?.replace(/\\/api\\/v1\\/?$/, "") ||
  "http://localhost:8000";

async function forward(req: NextRequest, segments: string[]) {
  const search = req.nextUrl.search || "";
  const target = `${BACKEND}/api/v1/${segments.join("/")}${search}`;

  const headers = new Headers();
  const contentType = req.headers.get("content-type");
  if (contentType) headers.set("content-type", contentType);
  const auth = req.headers.get("authorization");
  if (auth) headers.set("authorization", auth);

  let body: string | undefined;
  if (req.method !== "GET" && req.method !== "DELETE") {
    body = await req.text();
  }

  try {
    const res = await fetch(target, { method: req.method, headers, body, cache: "no-store" });
    const text = await res.text();
    return new NextResponse(text, {
      status: res.status,
      headers: { "content-type": res.headers.get("content-type") || "application/json" },
    });
  } catch {
    return NextResponse.json(
      { detail: "The application server is not reachable." },
      { status: 503 },
    );
  }
}

type Ctx = { params: Promise<{ path: string[] }> };

export async function GET(req: NextRequest, ctx: Ctx) {
  return forward(req, (await ctx.params).path);
}
export async function POST(req: NextRequest, ctx: Ctx) {
  return forward(req, (await ctx.params).path);
}
export async function PATCH(req: NextRequest, ctx: Ctx) {
  return forward(req, (await ctx.params).path);
}
export async function PUT(req: NextRequest, ctx: Ctx) {
  return forward(req, (await ctx.params).path);
}
export async function DELETE(req: NextRequest, ctx: Ctx) {
  return forward(req, (await ctx.params).path);
}
"""


def gen_api_proxy(fe: Path) -> None:
    """Write the single catch-all proxy and remove any previously faked routes."""
    api_dir = fe / "src" / "app" / "api" / "v1"

    # Delete the old fake layer if a previous build left it behind.
    if api_dir.exists():
        for stale in list(api_dir.rglob("route.ts")):
            stale.unlink(missing_ok=True)
        for stale_dir in sorted(api_dir.rglob("*"), reverse=True):
            if stale_dir.is_dir() and not any(stale_dir.iterdir()):
                stale_dir.rmdir()
    stale_db = fe / "src" / "lib" / "db.ts"
    stale_db.unlink(missing_ok=True)

    catch_all = api_dir / "[...path]"
    catch_all.mkdir(parents=True, exist_ok=True)
    (catch_all / "route.ts").write_text(_PROXY_ROUTE_TS, encoding="utf-8")


# ── Seed data: only ever the user's own ─────────────────────────────────


def _py_literal(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False) if not isinstance(value, bool) else str(value)


def gen_seed_script(spec: Any, be: Path) -> None:
    """Write backend/seed.py from spec.seed_data — never from a sample app.

    Runs on first start only, and only when the table is empty, so a user's
    real records are never overwritten by demo rows.
    """
    by_entity: dict[str, list[dict[str, Any]]] = {}
    for record in getattr(spec, "seed_data", []) or []:
        entity = str(getattr(record, "entity", ""))
        values = dict(getattr(record, "values", {}) or {})
        if entity and values:
            by_entity.setdefault(entity, []).append(values)

    entities = {str(getattr(e, "name", "")): e for e in getattr(spec, "entities", [])}

    lines = [
        "# @generated by AI Solution Builder",
        '"""Example rows for a brand-new, empty app.',
        "",
        "Only runs when a table is completely empty, so your own records are safe.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "import asyncio",
        "",
        "from sqlalchemy import func, select",
        "",
        "try:",
        "    from .db import AsyncSessionLocal, engine",
        "    from .models import Base",
        "    from . import models",
        "except (ImportError, ValueError):",
        "    from db import AsyncSessionLocal, engine",
        "    from models import Base",
        "    import models",
        "",
        "",
        "SEED: dict[str, list[dict]] = {",
    ]
    for entity_name, rows in by_entity.items():
        if entity_name not in entities:
            continue
        lines.append(f"    {entity_name!r}: [")
        for row in rows[:20]:
            lines.append(f"        {row!r},")
        lines.append("    ],")
    lines += [
        "}",
        "",
        "",
        "MODELS = {",
    ]
    for entity_name, entity in entities.items():
        cls = "".join(part.capitalize() for part in entity_name.split("_"))
        lines.append(f"    {entity_name!r}: models.{cls},")
    lines += [
        "}",
        "",
        "",
        "async def seed() -> None:",
        "    async with engine.begin() as conn:",
        "        await conn.run_sync(Base.metadata.create_all)",
        "    async with AsyncSessionLocal() as session:",
        "        for name, rows in SEED.items():",
        "            model = MODELS.get(name)",
        "            if model is None or not rows:",
        "                continue",
        "            existing = await session.scalar(select(func.count()).select_from(model))",
        "            if existing:",
        "                continue",
        "            for row in rows:",
        "                session.add(model(**row))",
        "        await session.commit()",
        "",
        "",
        'if __name__ == "__main__":',
        "    asyncio.run(seed())",
    ]
    (be / "seed.py").write_text("\n".join(lines) + "\n", encoding="utf-8")


# ── Frontend config so the proxy knows where the server is ──────────────


def wire_frontend_env(fe: Path) -> None:
    """Keep the browser on a relative path; the proxy reaches the server."""
    env_example = fe / ".env.example"
    content = (
        "# The browser always calls this app's own /api/v1 path.\n"
        "NEXT_PUBLIC_API_URL=/api/v1\n"
        "\n"
        "# Where the application server actually lives (used only on the server side).\n"
        "BACKEND_URL=http://localhost:8000\n"
    )
    env_example.write_text(content, encoding="utf-8")


_CLIENT_FALLBACK = re.compile(
    r'const API_BASE\s*=\s*[\s\S]*?;', re.MULTILINE
)

_SAFE_CLIENT_BASE = '''const API_BASE =
  process.env.NEXT_PUBLIC_API_URL && process.env.NEXT_PUBLIC_API_URL.trim() !== ""
    ? process.env.NEXT_PUBLIC_API_URL
    : "/api/v1";'''


def harden_api_client(fe: Path) -> None:
    """Always resolve to a real server; never to a page-local stub."""
    client = fe / "src" / "lib" / "api.ts"
    if not client.exists():
        return
    body = client.read_text(encoding="utf-8")
    if "const API_BASE" in body:
        body = _CLIENT_FALLBACK.sub(_SAFE_CLIENT_BASE, body, count=1)
        client.write_text(body, encoding="utf-8")


def wire_real_data_layer(spec: Any, root: Path) -> None:
    """Call this from write_generated in place of gen_next_route_handlers."""
    fe, be = root / "frontend", root / "backend"
    if fe.exists():
        gen_api_proxy(fe)
        wire_frontend_env(fe)
        harden_api_client(fe)
    if be.exists():
        gen_seed_script(spec, be)


# ── Honest action stubs ─────────────────────────────────────────────────
#
# The previous generator emitted `return <output_example>` for every action.
# The generated acceptance test asserted that same output_example, so the test
# passed against a hardcoded constant and the quality gate went green while the
# shipped app did nothing. A stub must FAIL until a real implementation lands.

_STUB_BODY = (
    '    raise HTTPException(\n'
    '        status_code=501,\n'
    '        detail="This part of the app has not been built yet.",\n'
    '    )'
)


def gen_actions_stub_strict(spec: Any) -> str:
    """Action module whose stubs fail loudly instead of faking an answer."""
    header = [
        '"""The parts of this app that do real work.',
        "",
        "Each function below must compute its answer from saved data, following",
        "the rules in spec.json. Until then it returns 501 so the acceptance",
        "tests fail — never a fixed example value, which would make the tests",
        "pass against an app that does nothing.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from typing import Any",
        "",
        "from fastapi import APIRouter, HTTPException",
        "from sqlalchemy import func, select",
        "",
        "try:",
        "    from . import models, schemas",
        "    from .deps import SessionDep",
        "except (ImportError, ValueError):",
        "    import models",
        "    import schemas",
        "    from deps import SessionDep",
        "",
        'router = APIRouter(tags=["actions"])',
    ]

    import re as _re

    body: list[str] = []
    for action in getattr(spec, "actions", []) or []:
        name = _re.sub(r"[^a-z0-9_]+", "_", str(getattr(action, "name", "")).lower()).strip("_")
        path = str(getattr(action, "path", ""))
        method = str(getattr(action, "method", "POST")).lower()
        rules = "\n".join(f"    - {r}" for r in getattr(action, "rules", []))

        params = ""
        for path_param in _re.findall(r"{(\w+)}", path):
            params += f"{path_param}: int, "
        if method == "post":
            cls = "".join(p.capitalize() for p in name.split("_"))
            params += f"payload: schemas.{cls}Input, "

        body += [
            "",
            "",
            f'@router.{method}("{path}")',
            f"async def {name}({params}session: SessionDep) -> dict[str, Any]:",
            f'    """{getattr(action, "summary", name)}',
            "",
            "    Rules:",
            rules,
            '    """',
            _STUB_BODY,
        ]
    if not body:
        body = ["", "", "# This app has no custom calculations — plain records only."]
    return "\n".join(header + body) + "\n"


def enforce_distinguishing_tests(spec: Any) -> list[str]:
    """Flag actions a constant answer could still satisfy.

    An action needs at least two acceptance scenarios whose expected results
    differ; otherwise `return <fixed value>` passes the suite and the gate
    proves nothing.
    """
    problems: list[str] = []
    tests = list(getattr(spec, "acceptance_tests", []) or [])

    for action in getattr(spec, "actions", []) or []:
        path = str(getattr(action, "path", ""))
        pattern = re.compile("^" + re.sub(r"\\\{\w+\\\}", "[^/]+", re.escape(path)) + "$")

        expectations: list[str] = []
        for test in tests:
            for step in getattr(test, "steps", []) or []:
                base = str(getattr(step, "path", "")).split("?")[0]
                if pattern.match(base):
                    expectations.append(
                        json.dumps(
                            {
                                "status": getattr(step, "expect_status", 200),
                                "expect": getattr(step, "expect", {}) or {},
                            },
                            sort_keys=True,
                        )
                    )

        if len(expectations) < 2:
            problems.append(
                f"Action '{getattr(action, 'name', '')}' has {len(expectations)} test scenario(s); "
                "needs at least 2 so a fixed answer cannot pass."
            )
        elif len(set(expectations)) < 2:
            problems.append(
                f"Action '{getattr(action, 'name', '')}' is tested twice with the same expected "
                "result; a hardcoded value would still pass."
            )
    return problems
