"""
AI Solution Builder — Synthetic Data Generator (Section 12 USP)

Auto-populates provisioned workable tables with realistic, localized dummy
records so generated systems can be clicked through immediately after
provisioning — no manual data entry required. Insertion order is
topologically sorted so foreign keys always resolve to real parent records.
"""

import logging
import random
import uuid
from datetime import UTC, datetime, timedelta
from typing import Any

from sqlalchemy import Column, Table, insert
from sqlalchemy import text as sa_text
from sqlalchemy.ext.asyncio import AsyncSession

from app.workable.engine import resolve_table

logger = logging.getLogger(__name__)

_FIRST_NAMES = [
    "Aarav",
    "Sneha",
    "Priya",
    "Rohan",
    "Ananya",
    "Vikram",
    "Meera",
    "Arjun",
    "Divya",
    "Kabir",
]
_LAST_NAMES = [
    "Sharma",
    "Patel",
    "Reddy",
    "Iyer",
    "Singh",
    "Gupta",
    "Nair",
    "Das",
    "Kulkarni",
    "Menon",
]
_SAMPLE_COMPANIES = [
    "Acme Consulting",
    "Horizon Solutions",
    "Vertex Retail",
    "Nimbus Logistics",
    "Crest Analytics",
]
_STATUS_WORDS = ["new", "active", "pending", "closed", "in_progress", "completed", "cancelled"]
_LOREM = [
    "Sample record generated by the Synthetic Data Generator.",
    "Realistic dummy data for immediate testing of the live system.",
    "Localized example entry suitable for demos and QA.",
    "Placeholder content that reflects the schema of the provisioned system.",
]


def _fk_reference(col: Column[Any]) -> Column[Any] | None:
    """Return the referenced column if `col` is a foreign key, else None."""
    fks = [fk for fk in col.foreign_keys if fk.column is not None]
    if not fks:
        return None
    return fks[0].column  # type: ignore[return-value]


def _value_for_column(
    col: Column[Any], rng: random.Random, row_index: int = 0
) -> Any:
    """Generate a plausible value for a column based on its name/type.

    ``row_index`` (and UUID-based salts for email/url) make values unique per
    row so UNIQUE constraints on email/url-style columns never collide.
    """
    name = col.name.lower()
    col_type = str(col.type).upper()

    if "UUID" in col_type:
        return uuid.uuid4()

    if "email" in name:
        return f"user-{uuid.uuid4().hex[:10]}@example.com"

    if "phone" in name or "mobile" in name:
        return f"+91{rng.randint(7000000000, 9999999999)}"

    if "url" in name or "website" in name:
        return f"https://{uuid.uuid4().hex[:8]}.example.com"

    if "status" in name or "state" in name:
        return rng.choice(_STATUS_WORDS)

    if "first_name" in name or "fname" in name:
        return rng.choice(_FIRST_NAMES)

    if "last_name" in name or "lname" in name:
        return rng.choice(_LAST_NAMES)

    if "name" in name or "title" in name:
        pool = (
            _SAMPLE_COMPANIES
            if "company" in name
            else [
                f"{w.capitalize()} item" for w in rng.sample(["red", "blue", "green", "orange"], 1)
            ]
        )
        return rng.choice(pool)

    if "description" in name or "notes" in name or "body" in name or "summary" in name:
        return rng.choice(_LOREM)

    if "BOOL" in col_type:
        return rng.random() > 0.3

    numeric_types = ("NUMERIC", "DECIMAL", "FLOAT", "DOUBLE")
    if "INT" in col_type or any(t in col_type for t in numeric_types):
        if "amount" in name or "price" in name or "revenue" in name or "cost" in name:
            return round(rng.uniform(100, 100000), 2)
        return rng.randint(1, 500)

    if "TIMESTAMP" in col_type or "DATE" in col_type:
        return datetime.now(UTC) - timedelta(days=rng.randint(0, 365))

    if "JSON" in col_type:
        return {"meta": "synthetic"}

    # Important: any NOT NULL column must get a value.
    return f"sample-{row_index}-{rng.randint(1000, 9999)}"


def _fk_value(
    col: Column[Any],
    entity: str,
    parent_pks: dict[str, list[Any]],
    rng: random.Random,
    row_index: int,
) -> Any:
    """Pick a real parent PK for a FK column, rotating across parents.

    Handles the two integrity traps in synthetic seeding:
    * empty parents (e.g. the very first row of a self-referencing table) —
      pass None when the column allows it, otherwise leave a valid-looking value
      (the database will reject truly invalid inserts, and the caller skips them).
    * FK columns pointing at tables not being seeded in this run.
    """
    ref = _fk_reference(col)
    if ref is None:
        return _value_for_column(col, rng, row_index)

    parent_name = ref.table.name
    if parent_name == entity or parent_name not in parent_pks or not parent_pks[parent_name]:
        if col.nullable:
            return None
        return _value_for_column(col, rng, row_index)

    candidates = parent_pks[parent_name]
    return candidates[rng.randrange(len(candidates))]


async def _schema_tables(db: AsyncSession, schema_name: str) -> list[str]:
    result = await db.execute(
        sa_text(
            "SELECT table_name FROM information_schema.tables "
            "WHERE table_schema = :schema AND table_type = 'BASE TABLE' ORDER BY table_name"
        ),
        {"schema": schema_name},
    )
    return [row[0] for row in result.all()]


def _topological_order(tables: dict[str, Table]) -> list[str]:
    """Order tables parents-first so FK inserts never reference empty tables."""
    visited: set[str] = set()
    visiting: set[str] = set()
    order: list[str] = []

    def visit(name: str) -> None:
        if name in visited or name in visiting:  # cycles fall back to alphabetical
            return
        visiting.add(name)
        for col in tables[name].columns:
            ref = _fk_reference(col)
            if ref is not None and ref.table.name in tables and ref.table.name != name:
                visit(ref.table.name)
        visiting.discard(name)
        visited.add(name)
        order.append(name)

    for name in sorted(tables):
        visit(name)
    return order


async def seed_synthetic_rows(
    db: AsyncSession,
    schema_name: str,
    modules: list[dict[str, Any]],
    rows_per_table: int = 5,
) -> int:
    """Insert synthetic rows into every entity table of the provisioned modules.

    Returns the total number of rows created. Foreign-key columns are filled
    with the primary keys of already-seeded parent rows so inserts never
    violate referential integrity.
    """
    table_names = await _schema_tables(db, schema_name)
    if not table_names:
        return 0

    tables: dict[str, Table] = {}
    for entity in table_names:
        tables[entity] = await resolve_table(db, schema_name, entity)

    created = 0
    parent_pks: dict[str, list[Any]] = {}

    for entity in _topological_order(tables):
        table = tables[entity]
        pk = next((c for c in table.columns if c.primary_key), None)
        writeable = [c for c in table.columns if c is not pk and not c.server_default]

        for row_index in range(rows_per_table):
            rng = random.Random()
            values: dict[str, Any] = {}
            for col in writeable:
                values[col.name] = _fk_value(col, entity, parent_pks, rng, row_index)

            try:
                if pk is not None:
                    stmt = insert(table).values(**values).returning(pk)
                    row = await db.execute(stmt)
                    parent_pks.setdefault(entity, []).append(row.scalar_one())
                else:
                    await db.execute(insert(table).values(**values))
            except Exception as exc:  # noqa: BLE001
                # One malformed row (e.g. NOT NULL FK to an unseeded parent) must not
                # abort the entire run — log and continue with the next row.
                logger.warning(
                    "Skipping synthetic row for %s.%s: %s", schema_name, entity, exc
                )
                continue
            created += 1

    await db.flush()
    logger.info(
        "Seeded %d synthetic rows across %d tables in %s",
        created,
        len(tables),
        schema_name,
    )
    return created
