'use client';

import React, { useCallback, useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import Link from 'next/link';
import {
  ArrowLeft,
  ArrowRight,
  Check,
  Loader2,
  Play,
  RefreshCw,
  Rocket,
} from 'lucide-react';
import { mvpApi, solutionApi } from '@/lib/api';
import { MVPBuild, MVPTemplate, Solution } from '@/types';
import { BuildCard, ConfigureModal, DeployModal } from '@/components/mvp/BuildCard';

const SAMPLE_TEMPLATES: MVPTemplate[] = [
  {
    slug: 'todo',
    title: 'Todo List Workspace',
    description: 'A minimal single-module CRUD app — items, tags, and completion states.',
    app_name: 'todo-app',
    industry: 'Productivity',
  },
  {
    slug: 'calculator',
    title: 'Calculator',
    description: 'A simple interactive calculator with a persistent history ledger.',
    app_name: 'calculator',
    industry: 'Utilities',
  },
  {
    slug: 'portfolio',
    title: 'Portfolio Site',
    description: 'A public-facing portfolio with project showcases and contact forms.',
    app_name: 'portfolio',
    industry: 'Web',
  },
];

export default function MvpPage() {
  const params = useParams();
  const solutionId = (params?.id as string) || 'sol-demo-1';

  const [solution, setSolution] = useState<Solution | null>(null);
  const [templates, setTemplates] = useState<MVPTemplate[]>([]);
  const [builds, setBuilds] = useState<MVPBuild[]>([]);
  const [selectedTemplate, setSelectedTemplate] = useState<string | null>('todo');
  const [appName, setAppName] = useState('');
  const [forceBuild, setForceBuild] = useState(false);
  const [starting, setStarting] = useState(false);
  const [actionError, setActionError] = useState<string | null>(null);
  const [deployTarget, setDeployTarget] = useState<MVPBuild | null>(null);
  const [configureTarget, setConfigureTarget] = useState<MVPBuild | null>(null);

  const loadBuilds = useCallback(async () => {
    try {
      setBuilds(await mvpApi.listBuilds(solutionId));
    } catch {
      // backend unavailable — keep current list
    }
  }, [solutionId]);

  useEffect(() => {
    solutionApi
      .get(solutionId)
      .then(setSolution)
      .catch(() => {
        setSolution({
          id: solutionId,
          workspace_id: 'ws-demo-1',
          title: 'Omnichannel Retail POS & Inventory Platform',
          description: 'Enterprise architecture generated by AI Solution Builder.',
          status: 'complete',
          created_at: new Date().toISOString(),
        });
      });
  }, [solutionId]);

  useEffect(() => {
    mvpApi
      .listTemplates()
      .then(setTemplates)
      .catch(() => setTemplates(SAMPLE_TEMPLATES));
  }, []);

  useEffect(() => {
    let cancelled = false;
    mvpApi
      .listBuilds(solutionId)
      .then((list) => {
        if (!cancelled) setBuilds(list);
      })
      .catch(() => undefined);
    return () => {
      cancelled = true;
    };
  }, [solutionId]);

  useEffect(() => {
    const hasActive = builds.some(
      (b) => b.status === 'pending' || b.status === 'queued' || b.status === 'building'
    );
    if (!hasActive) return;
    const timer = setInterval(loadBuilds, 3000);
    return () => clearInterval(timer);
  }, [builds, loadBuilds]);

  const handleStartBuild = async () => {
    setStarting(true);
    setActionError(null);
    try {
      await mvpApi.triggerBuild(solutionId, {
        app_name: appName.trim() || undefined,
        template: selectedTemplate || undefined,
        force: forceBuild,
      });
      setAppName('');
      await loadBuilds();
    } catch (err) {
      setActionError(err instanceof Error ? err.message : 'Failed to start build.');
    } finally {
      setStarting(false);
    }
  };

  const handleDownload = async (build: MVPBuild) => {
    try {
      await mvpApi.downloadBuild(build.build_id, `mvp_${build.solution_id.slice(0, 8)}_build${build.build_number}.zip`);
    } catch (err) {
      setActionError(err instanceof Error ? err.message : 'Download failed.');
    }
  };

  const handleDestroy = async (build: MVPBuild) => {
    if (!window.confirm(`Destroy build #${build.build_number}? The workspace will be deleted.`)) return;
    try {
      await mvpApi.destroy(build.build_id);
      await loadBuilds();
    } catch (err) {
      setActionError(err instanceof Error ? err.message : 'Destroy failed.');
    }
  };

  const handleDestroyPreview = async (build: MVPBuild) => {
    if (!window.confirm(`Tear down Render live application for build #${build.build_number}?`)) return;
    try {
      await mvpApi.destroyPreview(build.build_id);
      await loadBuilds();
    } catch (err) {
      setActionError(err instanceof Error ? err.message : 'Destroy preview failed.');
    }
  };

  const handleDeployed = () => {
    loadBuilds();
  };

  return (
    <div className="space-y-6 max-w-6xl mx-auto animate-fade-up">
      {/* Header Navigation */}
      <div className="flex items-center justify-between">
        <Link
          href={`/solution/${solutionId}`}
          className="inline-flex items-center gap-2 text-xs font-medium text-[#666] hover:text-white transition-colors"
        >
          <ArrowLeft className="w-4 h-4" />
          <span>Back to Blueprints</span>
        </Link>

        <div className="flex items-center gap-2 text-[11px] text-[#555]">
          <span>Deploy prep:</span>
          <Link
            href="/settings"
            className="px-2.5 py-1 rounded-lg bg-[#161616] hover:bg-[#1f1f1f] text-[#a1a1a1] text-xs font-medium border border-[#242424] transition-colors"
          >
            Save GitHub Token
          </Link>
        </div>
      </div>

      {/* Hero */}
      <div className="p-6 rounded-xl bg-[#111] border border-[#1a1a1a] space-y-2">
        <div className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded bg-[#161616] border border-[#242424] text-[#818cf8] text-xs font-medium">
          <Rocket className="w-3.5 h-3.5 text-[#6366f1]" />
          <span>MVP Builder</span>
        </div>
        <h1 className="text-xl font-semibold text-white">
          Build Deployable App from {solution?.title || 'Solution'}
        </h1>
        <p className="text-xs text-[#555] leading-relaxed max-w-2xl">
          Generate a working FastAPI + Next.js project from your validated blueprints, ready for GitHub push and Render auto-deploy.
        </p>
      </div>

      {/* Start New Build */}
      <div className="p-5 rounded-xl bg-[#111] border border-[#1a1a1a] space-y-4">
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-sm font-semibold text-white flex items-center gap-2">
              <Play className="w-4 h-4 text-[#4ade80]" />
              <span>Start a New Build</span>
            </h2>
            <p className="text-xs text-[#555] mt-0.5">
              Pick a starter template or supply an app name to trigger the MVP generation.
            </p>
          </div>
          <button
            onClick={loadBuilds}
            className="flex items-center gap-1 px-2.5 py-1 rounded-lg bg-[#161616] hover:bg-[#1f1f1f] text-xs font-medium text-[#a1a1a1] border border-[#242424] transition-colors"
          >
            <RefreshCw className="w-3 h-3" />
            <span>Refresh</span>
          </button>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
          {templates.map((tpl) => {
            const selected = selectedTemplate === tpl.slug;
            return (
              <button
                key={tpl.slug}
                onClick={() => setSelectedTemplate(selected ? null : tpl.slug)}
                className={`p-4 rounded-xl border text-left transition-colors ${selected
                    ? 'bg-[#161616] border-[#6366f1]'
                    : 'bg-[#0a0a0a] border border-[#1a1a1a] hover:border-[#2e2e2e]'
                  }`}
              >
                <div className="flex items-center justify-between">
                  <span className="text-xs font-semibold text-white">{tpl.title}</span>
                  {selected && <Check className="w-4 h-4 text-[#6366f1]" />}
                </div>
                <p className="text-[11px] text-[#555] mt-1 leading-relaxed">{tpl.description}</p>
                <div className="mt-2.5 flex items-center gap-2">
                  <span className="badge badge-gray text-[10px]">
                    {tpl.industry}
                  </span>
                  <code className="text-[10px] text-[#818cf8] font-mono">{tpl.app_name}</code>
                </div>
              </button>
            );
          })}
        </div>

        <div className="flex flex-col sm:flex-row items-stretch sm:items-end gap-3 pt-1">
          <div className="flex-1 space-y-1">
            <label className="text-xs font-medium text-[#a1a1a1]">App Name (optional)</label>
            <input
              value={appName}
              onChange={(e) => setAppName(e.target.value)}
              placeholder={`e.g. ${templates[0]?.app_name || 'my-app'}`}
              className="w-full px-3 py-2 rounded-lg bg-[#0a0a0a] border border-[#2e2e2e] text-white text-xs font-mono focus:outline-none focus:border-[#6366f1] transition-colors"
            />
          </div>
          <label className="flex items-center gap-2 text-xs text-[#a1a1a1] pb-2.5 cursor-pointer">
            <input
              type="checkbox"
              checked={forceBuild}
              onChange={(e) => setForceBuild(e.target.checked)}
              className="accent-[#6366f1] rounded"
            />
            Force build
          </label>
          <button
            onClick={handleStartBuild}
            disabled={starting || (!selectedTemplate && !appName.trim())}
            className="flex items-center gap-2 px-5 py-2 rounded-lg bg-[#6366f1] hover:bg-[#5558dd] text-white text-xs font-medium transition-colors disabled:opacity-40"
          >
            {starting ? <Loader2 className="w-4 h-4 animate-spin" /> : <Rocket className="w-4 h-4" />}
            <span>Start MVP Build</span>
          </button>
        </div>

        {actionError && (
          <p className="text-[11px] text-[#f87171] bg-[#ef444410] border border-[#ef444420] rounded-lg p-2 font-mono">{actionError}</p>
        )}
      </div>

      {/* Builds list */}
      <div className="space-y-3">
        <div>
          <h2 className="text-sm font-semibold text-white">Builds</h2>
          <p className="text-xs text-[#555] mt-0.5">
            {builds.length} build{builds.length === 1 ? '' : 's'} for this solution.
          </p>
        </div>

        {builds.length === 0 ? (
          <div className="p-8 rounded-xl bg-[#111] border border-dashed border-[#1a1a1a] text-center">
            <Rocket className="w-6 h-6 text-[#555] mx-auto mb-2" />
            <p className="text-xs text-[#555]">No builds yet — start your first MVP build above.</p>
          </div>
        ) : (
          builds.map((build) => (
            <BuildCard
              key={build.build_id}
              build={build}
              isDeployed={Boolean(build.repo_url)}
              onDeploy={() => setDeployTarget(build)}
              onConfigure={() => setConfigureTarget(build)}
              onDownload={() => handleDownload(build)}
              onDestroy={() => handleDestroy(build)}
              onDestroyPreview={() => handleDestroyPreview(build)}
            />
          ))
        )}
      </div>

      {deployTarget && <DeployModal build={deployTarget} onClose={() => setDeployTarget(null)} onDeployed={handleDeployed} />}
      {configureTarget && (
        <ConfigureModal build={configureTarget} onClose={() => setConfigureTarget(null)} onConfigured={loadBuilds} />
      )}

      {/* Footer CTA */}
      <div className="flex justify-end">
        <Link
          href="/chat"
          className="flex items-center gap-2 px-4 py-2 rounded-lg bg-[#161616] hover:bg-[#1f1f1f] text-xs font-medium text-[#a1a1a1] border border-[#242424] transition-colors"
        >
          <span>Iterate Blueprints with AI</span>
          <ArrowRight className="w-3.5 h-3.5" />
        </Link>
      </div>
    </div>
  );
}