'use client';

import React, { useCallback, useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import Link from 'next/link';
import {
  ArrowLeft,
  ArrowRight,
  Check,
  Loader2,
  Play,
  RefreshCw,
  Rocket,
} from 'lucide-react';
import { mvpApi, solutionApi } from '@/lib/api';
import { MVPBuild, MVPTemplate, Solution } from '@/types';
import { BuildCard, ConfigureModal, DeployModal } from '@/components/mvp/BuildCard';

const SAMPLE_TEMPLATES: MVPTemplate[] = [
  {
    slug: 'todo',
    title: 'Todo List Workspace',
    description: 'A minimal single-module CRUD app — items, tags, and completion states.',
    app_name: 'todo-app',
    industry: 'Productivity',
  },
  {
    slug: 'calculator',
    title: 'Calculator',
    description: 'A simple interactive calculator with a persistent history ledger.',
    app_name: 'calculator',
    industry: 'Utilities',
  },
  {
    slug: 'portfolio',
    title: 'Portfolio Site',
    description: 'A public-facing portfolio with project showcases and contact forms.',
    app_name: 'portfolio',
    industry: 'Web',
  },
];

export default function MvpPage() {
  const params = useParams();
  const solutionId = (params?.id as string) || 'sol-demo-1';

  const [solution, setSolution] = useState<Solution | null>(null);
  const [templates, setTemplates] = useState<MVPTemplate[]>([]);
  const [builds, setBuilds] = useState<MVPBuild[]>([]);
  const [selectedTemplate, setSelectedTemplate] = useState<string | null>('todo');
  const [appName, setAppName] = useState('');
  const [forceBuild, setForceBuild] = useState(false);
  const [starting, setStarting] = useState(false);
  const [actionError, setActionError] = useState<string | null>(null);
  const [deployTarget, setDeployTarget] = useState<MVPBuild | null>(null);
  const [configureTarget, setConfigureTarget] = useState<MVPBuild | null>(null);

  const loadBuilds = useCallback(async () => {
    try {
      setBuilds(await mvpApi.listBuilds(solutionId));
    } catch {
      // backend unavailable — keep current list
    }
  }, [solutionId]);

  useEffect(() => {
    solutionApi
      .get(solutionId)
      .then(setSolution)
      .catch(() => {
        setSolution({
          id: solutionId,
          workspace_id: 'ws-demo-1',
          title: 'Omnichannel Retail POS & Inventory Platform',
          description: 'Enterprise architecture generated by AI Solution Builder.',
          status: 'complete',
          created_at: new Date().toISOString(),
        });
      });
  }, [solutionId]);

  useEffect(() => {
    mvpApi
      .listTemplates()
      .then(setTemplates)
      .catch(() => setTemplates(SAMPLE_TEMPLATES));
  }, []);

  useEffect(() => {
    let cancelled = false;
    mvpApi
      .listBuilds(solutionId)
      .then((list) => {
        if (!cancelled) setBuilds(list);
      })
      .catch(() => undefined);
    return () => {
      cancelled = true;
    };
  }, [solutionId]);

  // Poll builds while any is active
  useEffect(() => {
    const hasActive = builds.some(
      (b) => b.status === 'pending' || b.status === 'queued' || b.status === 'building'
    );
    if (!hasActive) return;
    const timer = setInterval(loadBuilds, 3000);
    return () => clearInterval(timer);
  }, [builds, loadBuilds]);

  const handleStartBuild = async () => {
    setStarting(true);
    setActionError(null);
    try {
      await mvpApi.triggerBuild(solutionId, {
        app_name: appName.trim() || undefined,
        template: selectedTemplate || undefined,
        force: forceBuild,
      });
      setAppName('');
      await loadBuilds();
    } catch (err) {
      setActionError(err instanceof Error ? err.message : 'Failed to start build.');
    } finally {
      setStarting(false);
    }
  };

  const handleDownload = async (build: MVPBuild) => {
    try {
      await mvpApi.downloadBuild(build.build_id, `mvp_${build.solution_id.slice(0, 8)}_build${build.build_number}.zip`);
    } catch (err) {
      setActionError(err instanceof Error ? err.message : 'Download failed.');
    }
  };

  const handleDestroy = async (build: MVPBuild) => {
    if (!window.confirm(`Destroy build #${build.build_number}? The workspace will be deleted.`)) return;
    try {
      await mvpApi.destroy(build.build_id);
      await loadBuilds();
    } catch (err) {
      setActionError(err instanceof Error ? err.message : 'Destroy failed.');
    }
  };

  const handleDestroyPreview = async (build: MVPBuild) => {
    if (!window.confirm(`Tear down Render live application for build #${build.build_number}?`)) return;
    try {
      await mvpApi.destroyPreview(build.build_id);
      await loadBuilds();
    } catch (err) {
      setActionError(err instanceof Error ? err.message : 'Destroy preview failed.');
    }
  };

  const handleDeployed = () => {
    loadBuilds();
  };

  return (
    <div className="space-y-8 max-w-6xl mx-auto">
      {/* Header */}
      <div className="flex items-center justify-between">
        <Link
          href={`/solution/${solutionId}`}
          className="inline-flex items-center gap-2 text-xs font-semibold text-slate-400 hover:text-slate-200 transition-colors"
        >
          <ArrowLeft className="w-4 h-4" />
          <span>Back to Blueprints</span>
        </Link>

        <div className="flex items-center gap-2 text-[11px] text-slate-500">
          <span>Deploy prep:</span>
          <Link
            href="/settings"
            className="px-3 py-1.5 rounded-lg bg-white/5 hover:bg-white/10 text-slate-300 font-semibold border border-white/10 transition-colors"
          >
            Save GitHub Token
          </Link>
        </div>
      </div>

      {/* Hero */}
      <div className="p-8 rounded-3xl bg-gradient-to-r from-indigo-950/60 via-slate-900/80 to-purple-950/40 border border-white/5 shadow-2xl relative overflow-hidden">
        <div className="relative z-10 space-y-2 max-w-2xl">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-indigo-500/10 border border-indigo-500/20 text-indigo-300 text-xs font-semibold">
            <Rocket className="w-3.5 h-3.5 text-indigo-400" />
            <span>OpenCode MVP Builder</span>
          </div>
          <h2 className="text-2xl font-extrabold text-white tracking-tight">
            Build a Deployable App from {solution?.title || 'this Solution'}
          </h2>
          <p className="text-xs text-slate-300 leading-relaxed">
            Generate a working FastAPI + Next.js project from your validated blueprints, then push it straight to a fresh
            GitHub repo ready for a Render blueprint auto-deploy.
          </p>
        </div>
      </div>

      {/* Start New Build */}
      <div className="p-6 rounded-2xl bg-slate-900/40 border border-white/5 space-y-5">
        <div className="flex items-center justify-between">
          <div>
            <h3 className="text-base font-bold text-white flex items-center gap-2">
              <Play className="w-4 h-4 text-emerald-400" />
              <span>Start a New Build</span>
            </h3>
            <p className="text-xs text-slate-500 mt-0.5">
              Pick a starter template and the full-blueprint slot-fill takes care of the rest. Costs MVP-build credits.
            </p>
          </div>
          <button
            onClick={loadBuilds}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-white/5 hover:bg-white/10 text-[11px] font-semibold text-slate-300 border border-white/10 transition-colors"
          >
            <RefreshCw className="w-3 h-3" />
            <span>Refresh</span>
          </button>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {templates.map((tpl) => {
            const selected = selectedTemplate === tpl.slug;
            return (
              <button
                key={tpl.slug}
                onClick={() => setSelectedTemplate(selected ? null : tpl.slug)}
                className={`p-5 rounded-2xl border text-left transition-all ${
                  selected
                    ? 'bg-indigo-950/40 border-indigo-500/50 shadow-lg shadow-indigo-500/10'
                    : 'bg-slate-900/60 border-white/5 hover:border-white/15'
                }`}
              >
                <div className="flex items-center justify-between">
                  <span className="text-xs font-bold text-white">{tpl.title}</span>
                  {selected && <Check className="w-4 h-4 text-indigo-400" />}
                </div>
                <p className="text-[11px] text-slate-400 mt-1.5 leading-relaxed">{tpl.description}</p>
                <div className="mt-3 flex items-center gap-2">
                  <span className="px-2 py-0.5 rounded-full bg-white/5 border border-white/10 text-[10px] font-semibold text-slate-400">
                    {tpl.industry}
                  </span>
                  <code className="text-[10px] text-indigo-300 font-mono">{tpl.app_name}</code>
                </div>
              </button>
            );
          })}
        </div>

        <div className="flex flex-col sm:flex-row items-stretch sm:items-end gap-3">
          <div className="flex-1 space-y-1.5">
            <label className="text-xs font-semibold text-slate-300">App Name (optional)</label>
            <input
              value={appName}
              onChange={(e) => setAppName(e.target.value)}
              placeholder={`e.g. ${templates[0]?.app_name || 'my-app'}`}
              className="w-full px-4 py-3 rounded-xl bg-slate-900 border border-white/10 text-white text-xs font-mono focus:outline-none focus:border-indigo-500 transition-colors"
            />
          </div>
          <label className="flex items-center gap-2 text-xs text-slate-300 pb-3 cursor-pointer">
            <input
              type="checkbox"
              checked={forceBuild}
              onChange={(e) => setForceBuild(e.target.checked)}
              className="accent-indigo-500"
            />
            Force (solution not yet complete)
          </label>
          <button
            onClick={handleStartBuild}
            disabled={starting || (!selectedTemplate && !appName.trim())}
            className="flex items-center gap-2 px-7 py-3 rounded-xl bg-gradient-to-r from-indigo-600 via-purple-600 to-cyan-500 hover:opacity-95 text-white text-xs font-bold shadow-xl shadow-indigo-600/30 transition-all hover:scale-105 disabled:opacity-40"
          >
            {starting ? <Loader2 className="w-4 h-4 animate-spin" /> : <Rocket className="w-4 h-4" />}
            <span>Start MVP Build</span>
          </button>
        </div>

        {actionError && (
          <p className="text-[11px] text-rose-400 bg-rose-500/10 border border-rose-500/30 rounded-xl px-3 py-2">{actionError}</p>
        )}
      </div>

      {/* Builds */}
      <div className="space-y-4">
        <div>
          <h3 className="text-base font-bold text-white">Builds</h3>
          <p className="text-xs text-slate-500 mt-0.5">
            {builds.length} build{builds.length === 1 ? '' : 's'} for this solution. Status refreshes automatically while
            building.
          </p>
        </div>

        {builds.length === 0 ? (
          <div className="p-10 rounded-2xl bg-slate-900/40 border border-dashed border-white/10 text-center">
            <Rocket className="w-8 h-8 text-slate-600 mx-auto mb-2" />
            <p className="text-xs text-slate-500">No builds yet — start your first MVP build above.</p>
          </div>
        ) : (
          builds.map((build) => (
            <BuildCard
              key={build.build_id}
              build={build}
              isDeployed={Boolean(build.repo_url)}
              onDeploy={() => setDeployTarget(build)}
              onConfigure={() => setConfigureTarget(build)}
              onDownload={() => handleDownload(build)}
              onDestroy={() => handleDestroy(build)}
              onDestroyPreview={() => handleDestroyPreview(build)}
            />
          ))
        )}
      </div>

      {deployTarget && <DeployModal build={deployTarget} onClose={() => setDeployTarget(null)} onDeployed={handleDeployed} />}
      {configureTarget && (
        <ConfigureModal build={configureTarget} onClose={() => setConfigureTarget(null)} onConfigured={loadBuilds} />
      )}

      {/* Footer CTA */}
      <div className="flex justify-end">
        <Link
          href="/chat"
          className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-white/5 hover:bg-white/10 text-xs font-semibold text-slate-300 border border-white/10 transition-colors"
        >
          <span>Iterate Blueprints with AI</span>
          <ArrowRight className="w-3.5 h-3.5" />
        </Link>
      </div>
    </div>
  );
}