'use client';

import React, { useCallback, useEffect, useRef, useState } from 'react';
import { useParams } from 'next/navigation';
import Link from 'next/link';
import {
  ArrowLeft,
  ArrowRight,
  Check,
  Code,
  Loader2,
  MessageSquare,
  RefreshCw,
  Rocket,
  Send,
  Sparkles,
  Utensils,
} from 'lucide-react';
import { mvpApi, solutionApi, sendOpenCodeChatStream } from '@/lib/api';
import { MVPBuild, MVPTemplate, Solution } from '@/types';
import { BuildCard, ConfigureModal, DeployModal } from '@/components/mvp/BuildCard';
import ChatMessage from '@/components/ChatMessage';

interface ChatMsg {
  id: string;
  role: 'user' | 'assistant' | 'system';
  content: string;
  agent?: string;
}

let chatMsgCounter = 0;
function createMessageId(prefix: string): string {
  chatMsgCounter += 1;
  return `${prefix}-${chatMsgCounter}`;
}

const SAMPLE_TEMPLATES: MVPTemplate[] = [
  {
    slug: 'restaurant_ordering',
    title: 'Restaurant Menu & Ordering',
    description: 'Customer menu storefront, dynamic cart drawer, and live kitchen orders admin dashboard.',
    app_name: 'bistro-ordering',
    industry: 'Food & Beverage',
  },
  {
    slug: 'todo',
    title: 'Todo List Workspace',
    description: 'A minimal single-module CRUD app — items, tags, and completion states.',
    app_name: 'todo-app',
    industry: 'Productivity',
  },
  {
    slug: 'calculator',
    title: 'Calculator',
    description: 'A simple interactive calculator with a persistent history ledger.',
    app_name: 'calculator',
    industry: 'Utilities',
  },
  {
    slug: 'portfolio',
    title: 'Portfolio Site',
    description: 'A public-facing portfolio with project showcases and contact forms.',
    app_name: 'portfolio',
    industry: 'Web',
  },
];

const SUGGESTED_PROMPTS = [
  'Explain the system architecture and technicalities of this project.',
  'How does the customer menu, cart drawer & kitchen admin work?',
  'What database models, tables, and API endpoints are being created?',
  'Synthesize and prepare my custom solution build now.',
];

export default function MvpPage() {
  const params = useParams();
  const solutionId = (params?.id as string) || 'sol-demo-1';

  const [activeTab, setActiveTab] = useState<'chat' | 'templates' | 'builds'>('chat');
  const [solution, setSolution] = useState<Solution | null>(null);
  const [templates, setTemplates] = useState<MVPTemplate[]>(SAMPLE_TEMPLATES);
  const [builds, setBuilds] = useState<MVPBuild[]>([]);
  // Default to null so custom solution from blueprints/chat is the primary option
  const [selectedTemplate, setSelectedTemplate] = useState<string | null>(null);
  const [appName, setAppName] = useState('');
  const [forceBuild, setForceBuild] = useState(false);
  const [starting, setStarting] = useState(false);
  const [actionError, setActionError] = useState<string | null>(null);
  const [deployTarget, setDeployTarget] = useState<MVPBuild | null>(null);
  const [configureTarget, setConfigureTarget] = useState<MVPBuild | null>(null);

  // Chat State
  const [chatMessages, setChatMessages] = useState<ChatMsg[]>([]);
  const [chatInput, setChatInput] = useState('');
  const [isChatStreaming, setIsChatStreaming] = useState(false);
  const chatEndRef = useRef<HTMLDivElement>(null);

  const loadBuilds = useCallback(async () => {
    try {
      setBuilds(await mvpApi.listBuilds(solutionId));
    } catch {
      // backend unavailable — keep current list
    }
  }, [solutionId]);

  useEffect(() => {
    solutionApi
      .get(solutionId)
      .then((s) => {
        setSolution(s);
        setAppName(s.title || '');
        setChatMessages([
          {
            id: 'welcome-1',
            role: 'assistant',
            agent: 'AI Solution Architect',
            content: `Hello! I have loaded the architecture blueprints for **${s.title}**.\n\nYou can chat with me about the **technicalities** of your project—including database schemas, API routes, customer menu ordering flows, and admin kitchen boards—or ask questions before initiating your custom build.`,
          },
        ]);
      })
      .catch(() => {
        const fallbackTitle = 'Omnichannel Retail POS & Inventory Platform';
        setSolution({
          id: solutionId,
          workspace_id: 'ws-demo-1',
          title: fallbackTitle,
          description: 'Enterprise architecture generated by AI Solution Builder.',
          status: 'complete',
          created_at: new Date().toISOString(),
        });
        setAppName(fallbackTitle);
        setChatMessages([
          {
            id: 'welcome-1',
            role: 'assistant',
            agent: 'AI Solution Architect',
            content: `Hello! I have loaded your architecture blueprints for **${fallbackTitle}**.\n\nYou can chat with me about the **technicalities** of your project—including database schemas, API routes, and interactive components—before generating the build.`,
          },
        ]);
      });
  }, [solutionId]);

  useEffect(() => {
    mvpApi
      .listTemplates()
      .then((res) => {
        if (res && res.length > 0) setTemplates(res);
      })
      .catch(() => setTemplates(SAMPLE_TEMPLATES));
  }, []);

  useEffect(() => {
    let cancelled = false;
    mvpApi
      .listBuilds(solutionId)
      .then((list) => {
        if (!cancelled) setBuilds(list);
      })
      .catch(() => undefined);
    return () => {
      cancelled = true;
    };
  }, [solutionId]);

  useEffect(() => {
    const hasActive = builds.some(
      (b) => b.status === 'pending' || b.status === 'queued' || b.status === 'building'
    );
    if (!hasActive) return;
    const timer = setInterval(loadBuilds, 3000);
    return () => clearInterval(timer);
  }, [builds, loadBuilds]);

  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [chatMessages, isChatStreaming]);

  const handleSendMessage = async (textToSend?: string) => {
    const text = (textToSend || chatInput).trim();
    if (!text || isChatStreaming) return;

    setChatInput('');
    const userMsgId = createMessageId('user');
    const assistantMsgId = createMessageId('ai');

    setChatMessages((prev) => [
      ...prev,
      { id: userMsgId, role: 'user', content: text },
      { id: assistantMsgId, role: 'assistant', agent: 'AI Solution Architect', content: '' },
    ]);

    setIsChatStreaming(true);

    let accumulatedContent = '';

    try {
      await sendOpenCodeChatStream(
        {
          solution_id: solutionId,
          message: text,
          app_name: appName.trim() || solution?.title,
          build_requested: false,
        },
        {
          onEvent: (event, data) => {
            if (event === 'text_delta' && data?.text) {
              accumulatedContent += data.text;
              setChatMessages((prev) =>
                prev.map((m) =>
                  m.id === assistantMsgId ? { ...m, content: accumulatedContent } : m
                )
              );
            } else if (event === 'agent_start' && data?.message) {
              accumulatedContent = data.message + '\n\n';
              setChatMessages((prev) =>
                prev.map((m) =>
                  m.id === assistantMsgId ? { ...m, content: accumulatedContent } : m
                )
              );
            }
          },
          onComplete: (data) => {
            if (data?.message && !accumulatedContent) {
              setChatMessages((prev) =>
                prev.map((m) =>
                  m.id === assistantMsgId ? { ...m, content: data.message || '' } : m
                )
              );
            }
            setIsChatStreaming(false);
          },
          onError: (err) => {
            const errText =
              typeof err === 'object' && err && 'message' in err
                ? String((err as { message: string }).message)
                : 'Chat stream interrupted.';
            setChatMessages((prev) =>
              prev.map((m) =>
                m.id === assistantMsgId
                  ? {
                      ...m,
                      content:
                        accumulatedContent ||
                        `An error occurred communicating with the AI Architect: ${errText}`,
                    }
                  : m
              )
            );
            setIsChatStreaming(false);
          },
        }
      );
    } catch {
      setChatMessages((prev) =>
        prev.map((m) =>
          m.id === assistantMsgId && !m.content
            ? {
                ...m,
                content:
                  "I've received your inquiry. Your custom architecture is active and ready to be synthesized into a working FastAPI + Next.js build.",
              }
            : m
        )
      );
      setIsChatStreaming(false);
    }
  };

  const handleStartBuild = async () => {
    setStarting(true);
    setActionError(null);
    try {
      await mvpApi.triggerBuild(solutionId, {
        app_name: appName.trim() || solution?.title || undefined,
        template: selectedTemplate || undefined,
        force: forceBuild,
      });
      await loadBuilds();
      setActiveTab('builds');
    } catch (err) {
      setActionError(err instanceof Error ? err.message : 'Failed to start build.');
    } finally {
      setStarting(false);
    }
  };

  const handleDownload = async (build: MVPBuild) => {
    try {
      await mvpApi.downloadBuild(
        build.build_id,
        `mvp_${build.solution_id.slice(0, 8)}_build${build.build_number}.zip`
      );
    } catch (err) {
      setActionError(err instanceof Error ? err.message : 'Download failed.');
    }
  };

  const handleDestroy = async (build: MVPBuild) => {
    if (!window.confirm(`Destroy build #${build.build_number}? The workspace will be deleted.`)) return;
    try {
      await mvpApi.destroy(build.build_id);
      await loadBuilds();
    } catch (err) {
      setActionError(err instanceof Error ? err.message : 'Destroy failed.');
    }
  };

  const handleDestroyPreview = async (build: MVPBuild) => {
    if (!window.confirm(`Tear down Render live application for build #${build.build_number}?`)) return;
    try {
      await mvpApi.destroyPreview(build.build_id);
      await loadBuilds();
    } catch (err) {
      setActionError(err instanceof Error ? err.message : 'Destroy preview failed.');
    }
  };

  const handleDeployed = () => {
    loadBuilds();
  };

  return (
    <div className="space-y-6 max-w-6xl mx-auto animate-fade-up">
      {/* Header Navigation */}
      <div className="flex items-center justify-between">
        <Link
          href={`/solution/${solutionId}`}
          className="inline-flex items-center gap-2 text-xs font-medium text-[#666] hover:text-white transition-colors"
        >
          <ArrowLeft className="w-4 h-4" />
          <span>Back to Blueprints</span>
        </Link>

        <div className="flex items-center gap-2 text-[11px] text-[#555]">
          <span>Deploy prep:</span>
          <Link
            href="/settings"
            className="px-2.5 py-1 rounded-lg bg-[#161616] hover:bg-[#1f1f1f] text-[#a1a1a1] text-xs font-medium border border-[#242424] transition-colors"
          >
            Save GitHub Token
          </Link>
        </div>
      </div>

      {/* Hero */}
      <div className="p-6 rounded-xl bg-[#111] border border-[#1a1a1a] space-y-2">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <div className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded bg-[#161616] border border-[#242424] text-[#818cf8] text-xs font-medium">
            <Rocket className="w-3.5 h-3.5 text-[#6366f1]" />
            <span>MVP Builder &amp; Architect</span>
          </div>
          {selectedTemplate ? (
            <div className="inline-flex items-center gap-2 px-2.5 py-1 rounded bg-amber-950/40 border border-amber-800/40 text-amber-300 text-xs">
              <span>Using Template: <strong>{templates.find((t) => t.slug === selectedTemplate)?.title}</strong></span>
              <button
                onClick={() => setSelectedTemplate(null)}
                className="text-amber-400 hover:text-white ml-1 text-[11px] underline"
              >
                Switch to Custom Blueprints
              </button>
            </div>
          ) : (
            <div className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded bg-emerald-950/40 border border-emerald-800/40 text-emerald-300 text-xs font-medium">
              <Sparkles className="w-3.5 h-3.5 text-emerald-400" />
              <span>Custom Solution Mode (Active Blueprints)</span>
            </div>
          )}
        </div>

        <h1 className="text-xl font-semibold text-white">
          {solution?.title || 'Solution MVP Builder'}
        </h1>
        <p className="text-xs text-[#777] leading-relaxed max-w-3xl">
          Chat with the AI Architect to inspect technicalities, database schemas, and endpoints, or synthesize your domain-specific FastAPI backend + Next.js frontend with live customer storefront, cart, and admin kitchen display.
        </p>
      </div>

      {/* Navigation Tabs */}
      <div className="flex items-center gap-2 border-b border-[#222] pb-3">
        <button
          onClick={() => setActiveTab('chat')}
          className={`flex items-center gap-2 px-4 py-2 rounded-lg text-xs font-semibold transition-all ${
            activeTab === 'chat'
              ? 'bg-[#6366f1] text-white shadow-lg shadow-indigo-600/20'
              : 'bg-[#141414] text-[#888] hover:text-white border border-[#222]'
          }`}
        >
          <MessageSquare className="w-3.5 h-3.5" />
          <span>AI Architect &amp; Technicalities Chat</span>
        </button>

        <button
          onClick={() => setActiveTab('templates')}
          className={`flex items-center gap-2 px-4 py-2 rounded-lg text-xs font-semibold transition-all ${
            activeTab === 'templates'
              ? 'bg-[#6366f1] text-white shadow-lg shadow-indigo-600/20'
              : 'bg-[#141414] text-[#888] hover:text-white border border-[#222]'
          }`}
        >
          <Utensils className="w-3.5 h-3.5" />
          <span>Starter Templates (Optional)</span>
          {selectedTemplate && (
            <span className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse" />
          )}
        </button>

        <button
          onClick={() => setActiveTab('builds')}
          className={`flex items-center gap-2 px-4 py-2 rounded-lg text-xs font-semibold transition-all ${
            activeTab === 'builds'
              ? 'bg-[#6366f1] text-white shadow-lg shadow-indigo-600/20'
              : 'bg-[#141414] text-[#888] hover:text-white border border-[#222]'
          }`}
        >
          <Rocket className="w-3.5 h-3.5" />
          <span>Build History &amp; Deploys</span>
          <span className="rounded-full bg-[#222] px-2 py-0.5 text-[10px] text-[#aaa]">
            {builds.length}
          </span>
        </button>
      </div>

      {/* Action Error Banner */}
      {actionError && (
        <div className="p-3 rounded-lg bg-[#ef444415] border border-[#ef444430] text-xs text-red-400 font-mono">
          {actionError}
        </div>
      )}

      {/* Tab 1: AI Architect & Technicalities Chat */}
      {activeTab === 'chat' && (
        <div className="space-y-4">
          {/* Quick Prompts Bar */}
          <div className="flex flex-wrap items-center gap-2">
            <span className="text-[11px] font-semibold text-[#666] flex items-center gap-1">
              <Sparkles className="w-3 h-3 text-indigo-400" /> Suggested Technical Inquiries:
            </span>
            {SUGGESTED_PROMPTS.map((prompt) => (
              <button
                key={prompt}
                onClick={() => handleSendMessage(prompt)}
                disabled={isChatStreaming}
                className="text-[11px] px-2.5 py-1 rounded-full bg-[#161616] hover:bg-[#202020] text-[#aaa] hover:text-white border border-[#252525] transition-all disabled:opacity-40"
              >
                {prompt}
              </button>
            ))}
          </div>

          {/* Interactive Chat Window */}
          <div className="rounded-xl border border-[#1e1e1e] bg-[#0c0c0c] flex flex-col h-[520px] overflow-hidden shadow-2xl">
            {/* Chat Messages Stream */}
            <div className="flex-1 overflow-y-auto p-4 space-y-3">
              {chatMessages.map((msg) => (
                <ChatMessage
                  key={msg.id}
                  role={msg.role}
                  content={msg.content}
                  agent={msg.agent}
                />
              ))}
              {isChatStreaming && (
                <div className="flex items-center gap-2 text-xs text-indigo-400 p-2 font-mono animate-pulse">
                  <Loader2 className="w-3.5 h-3.5 animate-spin" />
                  <span>AI Architect is analyzing codebase technicalities...</span>
                </div>
              )}
              <div ref={chatEndRef} />
            </div>

            {/* Chat Input Bar */}
            <div className="border-t border-[#1e1e1e] bg-[#111] p-3">
              <form
                onSubmit={(e) => {
                  e.preventDefault();
                  handleSendMessage();
                }}
                className="flex items-center gap-2"
              >
                <input
                  value={chatInput}
                  onChange={(e) => setChatInput(e.target.value)}
                  placeholder="Ask the AI Architect anything about models, APIs, frontend UI, or build technicalities..."
                  disabled={isChatStreaming}
                  className="flex-1 bg-[#0a0a0a] border border-[#252525] focus:border-[#6366f1] rounded-lg px-3.5 py-2 text-xs text-white placeholder-[#555] focus:outline-none transition-all"
                />
                <button
                  type="submit"
                  disabled={isChatStreaming || !chatInput.trim()}
                  className="flex items-center gap-1.5 px-4 py-2 bg-[#6366f1] hover:bg-[#5558dd] text-white text-xs font-semibold rounded-lg transition-colors disabled:opacity-40"
                >
                  <Send className="w-3.5 h-3.5" />
                  <span>Send</span>
                </button>
              </form>
            </div>
          </div>

          {/* Direct Synthesis & Build Action Box */}
          <div className="p-5 rounded-xl bg-gradient-to-r from-[#121217] to-[#0f1118] border border-indigo-950/60 flex flex-col sm:flex-row items-stretch sm:items-center justify-between gap-4 shadow-xl">
            <div className="space-y-1">
              <h3 className="text-sm font-bold text-white flex items-center gap-2">
                <Code className="w-4 h-4 text-indigo-400" />
                <span>Ready to Generate This Solution?</span>
              </h3>
              <p className="text-xs text-[#888] max-w-xl">
                {selectedTemplate
                  ? `Build using the selected starter template (${selectedTemplate}).`
                  : 'Synthesize custom domain models, interactive storefront, cart drawer, and admin kitchen board directly from your solution blueprint.'}
              </p>
            </div>

            <div className="flex items-center gap-3">
              <button
                onClick={handleStartBuild}
                disabled={starting}
                className="flex items-center justify-center gap-2 px-6 py-2.5 rounded-lg bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-bold shadow-lg shadow-emerald-600/30 transition-all disabled:opacity-50"
              >
                {starting ? (
                  <Loader2 className="w-4 h-4 animate-spin" />
                ) : (
                  <Rocket className="w-4 h-4" />
                )}
                <span>
                  {selectedTemplate ? 'Build Selected Template' : 'Synthesize & Build Custom Solution'}
                </span>
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Tab 2: Starter Templates (Optional) */}
      {activeTab === 'templates' && (
        <div className="space-y-4">
          <div className="p-4 rounded-xl bg-[#111] border border-[#1a1a1a] flex items-center justify-between">
            <div>
              <h2 className="text-sm font-semibold text-white">Starter Templates (Optional Preset)</h2>
              <p className="text-xs text-[#666] mt-0.5">
                Select a preset if you want a quick bootstrap. Otherwise, keep it deselected to build your custom solution.
              </p>
            </div>
            {selectedTemplate && (
              <button
                onClick={() => setSelectedTemplate(null)}
                className="text-xs text-amber-400 hover:text-amber-300 font-semibold underline"
              >
                Deselect (Use Custom Blueprints)
              </button>
            )}
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-3">
            {templates.map((tpl) => {
              const selected = selectedTemplate === tpl.slug;
              return (
                <button
                  key={tpl.slug}
                  onClick={() => setSelectedTemplate(selected ? null : tpl.slug)}
                  className={`p-4 rounded-xl border text-left transition-all ${
                    selected
                      ? 'bg-[#181824] border-[#6366f1] ring-1 ring-[#6366f1]'
                      : 'bg-[#0a0a0a] border-[#1a1a1a] hover:border-[#2e2e2e]'
                  }`}
                >
                  <div className="flex items-center justify-between">
                    <span className="text-xs font-semibold text-white">{tpl.title}</span>
                    {selected && <Check className="w-4 h-4 text-[#6366f1]" />}
                  </div>
                  <p className="text-[11px] text-[#666] mt-1.5 leading-relaxed">{tpl.description}</p>
                  <div className="mt-3 flex items-center gap-2">
                    <span className="rounded bg-[#1a1a1a] px-2 py-0.5 text-[10px] text-[#aaa]">
                      {tpl.industry}
                    </span>
                    <code className="text-[10px] text-[#818cf8] font-mono">{tpl.app_name}</code>
                  </div>
                </button>
              );
            })}
          </div>

          <div className="flex flex-col sm:flex-row items-stretch sm:items-end gap-3 p-4 rounded-xl bg-[#111] border border-[#1a1a1a]">
            <div className="flex-1 space-y-1">
              <label className="text-xs font-medium text-[#a1a1a1]">App Name Override (optional)</label>
              <input
                value={appName}
                onChange={(e) => setAppName(e.target.value)}
                placeholder={solution?.title || 'my-app'}
                className="w-full px-3 py-2 rounded-lg bg-[#0a0a0a] border border-[#2e2e2e] text-white text-xs font-mono focus:outline-none focus:border-[#6366f1] transition-colors"
              />
            </div>
            <label className="flex items-center gap-2 text-xs text-[#a1a1a1] pb-2.5 cursor-pointer">
              <input
                type="checkbox"
                checked={forceBuild}
                onChange={(e) => setForceBuild(e.target.checked)}
                className="accent-[#6366f1] rounded"
              />
              Force fresh workspace
            </label>
            <button
              onClick={handleStartBuild}
              disabled={starting}
              className="flex items-center gap-2 px-5 py-2 rounded-lg bg-[#6366f1] hover:bg-[#5558dd] text-white text-xs font-medium transition-colors disabled:opacity-40"
            >
              {starting ? <Loader2 className="w-4 h-4 animate-spin" /> : <Rocket className="w-4 h-4" />}
              <span>{selectedTemplate ? 'Start Template Build' : 'Start Custom Build'}</span>
            </button>
          </div>
        </div>
      )}

      {/* Tab 3: Build History & Deploys */}
      {activeTab === 'builds' && (
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <div>
              <h2 className="text-sm font-semibold text-white">Generated Builds</h2>
              <p className="text-xs text-[#666] mt-0.5">
                {builds.length} build{builds.length === 1 ? '' : 's'} recorded for this solution.
              </p>
            </div>
            <button
              onClick={loadBuilds}
              className="flex items-center gap-1 px-3 py-1.5 rounded-lg bg-[#161616] hover:bg-[#1f1f1f] text-xs font-medium text-[#a1a1a1] border border-[#242424] transition-colors"
            >
              <RefreshCw className="w-3 h-3" />
              <span>Refresh Builds</span>
            </button>
          </div>

          {builds.length === 0 ? (
            <div className="p-10 rounded-xl bg-[#111] border border-dashed border-[#1a1a1a] text-center space-y-3">
              <Rocket className="w-8 h-8 text-[#555] mx-auto" />
              <p className="text-xs text-[#777]">No builds recorded yet.</p>
              <button
                onClick={() => setActiveTab('chat')}
                className="px-4 py-2 bg-[#6366f1] hover:bg-[#5558dd] text-white text-xs font-semibold rounded-lg transition-colors"
              >
                Go to AI Architect Chat to Build
              </button>
            </div>
          ) : (
            builds.map((build) => (
              <BuildCard
                key={build.build_id}
                build={build}
                isDeployed={Boolean(build.repo_url)}
                onDeploy={() => setDeployTarget(build)}
                onConfigure={() => setConfigureTarget(build)}
                onDownload={() => handleDownload(build)}
                onDestroy={() => handleDestroy(build)}
                onDestroyPreview={() => handleDestroyPreview(build)}
              />
            ))
          )}
        </div>
      )}

      {deployTarget && (
        <DeployModal
          build={deployTarget}
          onClose={() => setDeployTarget(null)}
          onDeployed={handleDeployed}
        />
      )}

      {configureTarget && (
        <ConfigureModal
          build={configureTarget}
          onClose={() => setConfigureTarget(null)}
          onConfigured={loadBuilds}
        />
      )}

      {/* Footer Navigation CTA */}
      <div className="flex justify-between items-center pt-4 border-t border-[#1a1a1a]">
        <Link
          href={`/solution/${solutionId}`}
          className="text-xs text-[#666] hover:text-white transition-colors"
        >
          ← Return to Architecture Blueprints
        </Link>
        <Link
          href={`/chat?solution_id=${solutionId}&app_name=${encodeURIComponent(solution?.title || 'Solution')}`}
          className="flex items-center gap-2 px-4 py-2 rounded-lg bg-[#161616] hover:bg-[#1f1f1f] text-xs font-medium text-[#a1a1a1] border border-[#242424] transition-colors"
        >
          <span>Open Fullscreen Studio Chat</span>
          <ArrowRight className="w-3.5 h-3.5" />
        </Link>
      </div>
    </div>
  );
}