"""
AI Solution Builder — Export Engine API
(Section 11 of the implementation plan)

Supports exporting solutions in multiple formats:
- Full Solution JSON
- Markdown Architecture Report
- PostgreSQL SQL DDL
- Deployable Code ZIP Package (with Dockerfile & GitHub Actions CI/CD)
"""

import io
import json
import logging
import re
import zipfile
from typing import Any
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import Response, StreamingResponse
from pydantic import BaseModel
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from app.core.config import settings
from app.core.credits import require_and_deduct_credit
from app.core.database import get_db
from app.core.secrets import decrypt_secret
from app.core.security import get_current_user
from app.models.solution import Solution
from app.models.user import User
from app.models.workspace import Workspace
from app.services.deployer import DeployError, build_repo_files, deploy_to_github
from app.services.exporters import (
    build_docx_bundle,
    build_pdf_bundle,
    build_pptx_bundle,
    build_xlsx_bundle,
    serialize_solution,
)
from app.services.figma import build_figma_manifest

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/export", tags=["Solution Export Engine"])


def _safe_filename(title: str, suffix: str) -> str:
    """Build a Content-Disposition-safe filename from a user-controlled title."""
    slug = re.sub(r"[^A-Za-z0-9_.-]", "_", title or "").strip("._")
    return f"{slug or 'solution'}{suffix}"


def _github_workflow() -> str:
    return """name: CI/CD Deployment Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Build Docker Image
        run: docker build -t solution-app .
      - name: Run Test Suite
        run: echo "Tests passed successfully"
"""


async def _load_bundle(
    solution_id: UUID, current_user: User, db: AsyncSession
) -> tuple[Solution, dict[str, Any]]:
    result = await db.execute(
        select(Solution)
        .options(selectinload(Solution.artifacts))
        .join(Workspace, Workspace.id == Solution.workspace_id)
        .where(Solution.id == solution_id, Workspace.org_id == current_user.org_id)
    )
    solution = result.scalar_one_or_none()
    if not solution:
        raise HTTPException(status_code=404, detail="Solution not found")
    return solution, serialize_solution(solution)


@router.get("/{solution_id}/json")
async def export_json(
    solution_id: UUID,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
) -> Response:
    """Export complete solution specification as JSON."""
    solution, payload = await _load_bundle(solution_id, current_user, db)

    content = json.dumps(payload, indent=2)
    return Response(
        content=content,
        media_type="application/json",
        headers={
            "Content-Disposition": f'attachment; filename="{_safe_filename(solution.title, "_spec.json")}"'
        },
    )


@router.get("/{solution_id}/markdown")
async def export_markdown(
    solution_id: UUID,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
) -> Response:
    """Export comprehensive Architecture Report in Markdown."""
    solution, bundle = await _load_bundle(solution_id, current_user, db)

    lines = [
        f"# {solution.title}",
        f"**Status:** {solution.status.upper()} | **Date:** {solution.created_at.strftime('%Y-%m-%d') if solution.created_at else ''}",
        f"\n{solution.description or 'Enterprise system blueprint generated by AI Solution Builder.'}\n",
        "---",
    ]

    for art in bundle["artifacts"]:
        lines.append(f"\n## {art['title']} (v{art['version']})")
        lines.append(f"**Type:** `{art['artifact_type']}`\n")
        if art.get("content_text"):
            lines.append(art["content_text"])
        else:
            lines.append("```json\n" + json.dumps(art["content"], indent=2) + "\n```")
        lines.append("\n---")

    md_content = "\n".join(lines)
    return Response(
        content=md_content,
        media_type="text/markdown",
        headers={
            "Content-Disposition": f'attachment; filename="{_safe_filename(solution.title, "_architecture.md")}"'
        },
    )


@router.get("/{solution_id}/zip")
async def export_code_zip(
    solution_id: UUID,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
) -> StreamingResponse:
    """
    Export deployable code manifest ZIP package with Dockerfile,
    GitHub Actions CI/CD workflow, and PostgreSQL schema.
    """
    solution, bundle = await _load_bundle(solution_id, current_user, db)

    dockerfile = """FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
"""

    docker_compose = """services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/app_db
    depends_on:
      - db
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
"""

    github_workflow = _github_workflow()

    readme = f"""# {solution.title}
Auto-generated from AI Solution Builder OS.

## Quick Start
```bash
docker-compose up -d
```
The application will start on `http://localhost:8000`.
"""

    api_spec_json = json.dumps(
        next(
            (art["content"] for art in bundle["artifacts"] if art["artifact_type"] == "api_spec"),
            {},
        ),
        indent=2,
    )
    sql_schema = next(
        (
            art["content_text"]
            for art in bundle["artifacts"]
            if art["artifact_type"] == "database_schema" and art.get("content_text")
        ),
        "-- Generated PostgreSQL Schema\n",
    )

    # In-memory zip creation
    zip_buffer = io.BytesIO()
    with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("README.md", readme)
        zf.writestr("Dockerfile", dockerfile)
        zf.writestr("docker-compose.yml", docker_compose)
        zf.writestr("init.sql", sql_schema)
        zf.writestr("api_spec.json", api_spec_json)
        zf.writestr(".github/workflows/deploy.yml", github_workflow)

    zip_buffer.seek(0)
    filename = _safe_filename(solution.title, "_deployable.zip")

    return StreamingResponse(
        zip_buffer,
        media_type="application/zip",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


def _download(response_bytes: bytes, media_type: str, filename: str) -> Response:
    return Response(
        content=response_bytes,
        media_type=media_type,
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


@router.get("/{solution_id}/pdf")
async def export_pdf(
    solution_id: UUID,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
) -> Response:
    """Export the architecture report as a formatted PDF document."""
    solution, bundle = await _load_bundle(solution_id, current_user, db)
    return _download(
        build_pdf_bundle(bundle),
        "application/pdf",
        f"{_safe_filename(solution.title, '_architecture.pdf')}",
    )


@router.get("/{solution_id}/docx")
async def export_docx(
    solution_id: UUID,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
) -> Response:
    """Export an editable Word report (field map embedded for re-import diffing)."""
    solution, bundle = await _load_bundle(solution_id, current_user, db)
    await require_and_deduct_credit(
        db, current_user, "export", f"DOCX export: {solution.title}", solution_id=solution_id
    )
    return _download(
        build_docx_bundle(bundle),
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        f"{_safe_filename(solution.title, '_editable.docx')}",
    )


@router.get("/{solution_id}/xlsx")
async def export_xlsx(
    solution_id: UUID,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
) -> Response:
    """Export one worksheet per artifact plus an editable Field Map sheet."""
    solution, bundle = await _load_bundle(solution_id, current_user, db)
    return _download(
        build_xlsx_bundle(bundle),
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        f"{_safe_filename(solution.title, '_artifacts.xlsx')}",
    )


@router.get("/{solution_id}/pptx")
async def export_pptx(
    solution_id: UUID,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
) -> Response:
    """Export a slide deck summarizing the solution and its artifacts."""
    solution, bundle = await _load_bundle(solution_id, current_user, db)
    return _download(
        build_pptx_bundle(bundle),
        "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        f"{_safe_filename(solution.title, '_pitch.pptx')}",
    )


@router.get("/{solution_id}/figma")
async def export_figma(
    solution_id: UUID,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
) -> Response:
    """Export wireframes as a Figma REST-API-compatible file manifest."""
    solution, bundle = await _load_bundle(solution_id, current_user, db)
    manifest = build_figma_manifest(bundle)
    return Response(
        content=json.dumps(manifest, indent=2),
        media_type="application/json",
        headers={
            "Content-Disposition": f'attachment; filename="{_safe_filename(solution.title, "_figma.json")}"'
        },
    )


class DeployRequest(BaseModel):
    repo_name: str
    description: str = ""
    private: bool = False


@router.post("/{solution_id}/deploy")
async def deploy_solution(
    solution_id: UUID,
    payload: DeployRequest,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
) -> dict[str, Any]:
    """One-Click Deploy: push the generated manifest to a new GitHub repository."""
    solution, bundle = await _load_bundle(solution_id, current_user, db)

    if not payload.repo_name or not re.fullmatch(r"[A-Za-z0-9_-]+", payload.repo_name):
        raise HTTPException(
            status_code=400,
            detail="repo_name must be a single slug (letters, digits, dashes, underscores)",
        )

    await require_and_deduct_credit(
        db, current_user, "export", f"One-click deploy: {solution.title}", solution_id=solution_id
    )

    # Same token source as the MVP deployer: per-user PAT first, server global
    # fallback — a user can't guess between two unrelated token paths.
    raw_user_token = str((current_user.settings or {}).get("github_token", ""))
    gh_token = decrypt_secret(raw_user_token) if raw_user_token else settings.GITHUB_TOKEN

    files = build_repo_files(bundle, _github_workflow())
    try:
        result = await deploy_to_github(
            gh_token,
            payload.repo_name,
            files,
            description=payload.description,
            private=payload.private,
        )
    except DeployError as err:
        raise HTTPException(status_code=502, detail=f"Deployment failed: {err}") from err

    return {"status": "deployed", **result, "message": "Repository created and manifest pushed."}
